# SPDX-FileCopyrightText: 2026 ReallyMe LLC
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "reallyme-platform"
description = "Application architecture for taking Rust services from framework to production"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["application", "architecture", "server", "connect-rpc", "cloudflare-workers"]
categories = ["asynchronous", "development-tools", "web-programming"]
publish = ["crates-io"]
readme = "README.md"
include = ["/src/**/*.rs", "/Cargo.toml", "/README.md"]

[features]
default = []
native-server = ["dep:reallyme-server-kit", "reallyme-server-kit/default"]
foundationdb = ["dep:reallyme-foundationdb-kit"]
nats = ["dep:reallyme-nats-kit"]
postgres = ["dep:reallyme-postgres-kit"]
s3 = ["dep:reallyme-s3-kit"]
typesense = ["dep:reallyme-typesense-kit"]
valkey = ["dep:reallyme-valkey-kit"]

[dependencies]
reallyme-app-kit.workspace = true
reallyme-foundationdb-kit = { workspace = true, optional = true }
reallyme-nats-kit = { workspace = true, optional = true }
reallyme-postgres-kit = { workspace = true, optional = true }
reallyme-s3-kit = { workspace = true, optional = true }
reallyme-server-kit = { workspace = true, optional = true }
reallyme-typesense-kit = { workspace = true, optional = true }
reallyme-valkey-kit = { workspace = true, optional = true }

[lints]
workspace = true
