# SPDX-FileCopyrightText: 2026 ReallyMe LLC
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "example-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
build = "build.rs"

[dependencies]
axum.workspace = true
reallyme-app-kit.workspace = true
example-app = { workspace = true, features = ["connect-axum", "native-server", "websocket"] }
reallyme-server-kit = { workspace = true, default-features = false, features = ["http", "websocket"] }
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
